<a href="https://colab.research.google.com/github/sukkyun2/big-data-visualization-and-analysis/blob/main/01.Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Practical Exercises

In [ ]:
import numpy as np

### Task 1
- Create an array filled with a single value (55)  
- Hint: Use np.full() function

In [ ]:
zeros = np.zeros((3, 3))  # 3X3 0으로 초기화

zeros.fill(55)  # 3X3 55로 초기화
zeros

array([[55., 55., 55.],
       [55., 55., 55.],
       [55., 55., 55.]])

### Task 2
- Create a null vector of size 10 but the fifth value which is 1

In [ ]:
zeros = np.zeros(10)  # 모두 0으로 초기화
zeros[4] = 1  # 4번째 인덱스에 1대입

zeros

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

### Task 3
- Reverse a vector

In [ ]:
arange = np.arange(10)  # 0~9 초기화
reversed = np.flip(arange)  # 역순으로 뒤집기
reversed

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

### Task 4
- Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
np.arange(9).reshape((3, 3))  # 0~8 초기화 후 3X3으로 reshape

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### Task 5
- Create a 5x5 matrix with row values ranging from 0 to 4  
- Requirements: Use only np.zeros and np.arange

In [ ]:
zeros = np.zeros((5, 5)) # 5x5 0으로 초기화

# row 개수만큼 반복하면서 0~4 ndarray를 재할당
for i in range(zeros.shape[0]):
        zeros[i] = np.arange(5)
zeros

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

### Task 6
- Create a 3D array with zeros along the second axis

### Task 7
- Given the following two arrays, add them

```python
array = np.array([
        [3, 2, 8],
        [4, 12, 34],
        [23, 12, 67]
])
newRow = np.array([2, 1, 8])
```


In [ ]:
array = np.array([
        [3, 2, 8],
        [4, 12, 34],
        [23, 12, 67]
])
newRow = np.array([2, 1, 8])

concatenate = np.vstack((array, newRow)) # 수직방향으로 ndarr 추가
concatenate

array([[ 3,  2,  8],
       [ 4, 12, 34],
       [23, 12, 67],
       [ 2,  1,  8]])

### Task 8
- Given the following arrays, calculate ((A+B)*(-A/2))
- Requirements: Use add(), multiply() and other functions


In [ ]:
A = np.ones(3) * 1
B = np.ones(3) * 2

# ((A+B)*(-A/2))
multiply = np.multiply(np.add(A, B), -A / 2)
multiply

array([-1.5, -1.5, -1.5])

### Task 9
- Calculate mean of each row of the list

In [ ]:
list = [
  np.array([3, 2, 8, 9]),
  np.array([4, 12, 34, 25, 78]),
  np.array([23, 12, 67])
]

[np.mean(list[i]) for i in range(len(list))] # list 개수만큼 반복하면서 평균 계산

[5.5, 30.6, 34.0]

### Task 10 (Optional)
- How to print the following pattern of nxn using NumPy?


In [ ]:
zeros = np.zeros((8,8)) # 8,8 0으로 초기화

for i in range(zeros.shape[0]):
    is_odd_row = i % 2 == 1  # 홀수 행인지 확인
    for j in range(zeros.shape[1]):
      if is_odd_row and j % 2 == 0:
        zeros[i, j] = 1
      elif not is_odd_row and j % 2 == 1:
        zeros[i, j] = 1

zeros

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])